// @generated by protoc-gen-es v2.6.0
// @generated from file user.proto (package users, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file user.proto.
 */
export const file_user = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEgV1c2VycyIHCgVFbXB0eSJVCgRVc2VyEgoKAmlkGAEgASgJEhEKCWZpcnN0TmFtZRgCIAEoCRIQCghsYXN0TmFtZRgDIAEoCRIPCgdlbWlhbElkGAQgASgJEgsKA2FnZRgFIAEoBSJFChFDcmVhdGVVc2VyUmVxdWVzdBIRCglmaXJzdE5hbWUYASABKAkSEAoIbGFzdE5hbWUYAiABKAkSCwoDYWdlGAMgASgFIiwKEVVwZGF0ZVVzZXJSZXF1ZXN0EgoKAmlkGAEgASgJEgsKA2FnZRgCIAEoBSIlChdHZXRBbmREZWxldGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoCSIlChJEZWxldGVVc2VyUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCIKCghMaXN0VXNlciIvChFMaXN0VXNlcnNSZXNwb25zZRIaCgV1c2VycxgBIAMoCzILLnVzZXJzLlVzZXIytgIKC1VzZXJTZXJ2aWNlEjMKCkNyZWF0ZVVzZXISGC51c2Vycy5DcmVhdGVVc2VyUmVxdWVzdBoLLnVzZXJzLlVzZXISOgoLR2V0VXNlckJ5SWQSHi51c2Vycy5HZXRBbmREZWxldGVVc2VyUmVxdWVzdBoLLnVzZXJzLlVzZXISMwoKVXBkYXRlVXNlchIYLnVzZXJzLlVwZGF0ZVVzZXJSZXF1ZXN0GgsudXNlcnMuVXNlchI4CgtHZXRVc2VyTGlzdBIPLnVzZXJzLkxpc3RVc2VyGhgudXNlcnMuTGlzdFVzZXJzUmVzcG9uc2USRwoKRGVsZXRlVXNlchIeLnVzZXJzLkdldEFuZERlbGV0ZVVzZXJSZXF1ZXN0GhkudXNlcnMuRGVsZXRlVXNlclJlc3BvbnNlYgZwcm90bzM");

/**
 * Describes the message users.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * Describes the message users.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * Describes the message users.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * Describes the message users.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 3);

/**
 * Describes the message users.GetAndDeleteUserRequest.
 * Use `create(GetAndDeleteUserRequestSchema)` to create a new message.
 */
export const GetAndDeleteUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 4);

/**
 * Describes the message users.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema = /*@__PURE__*/
  messageDesc(file_user, 5);

/**
 * Describes the message users.ListUser.
 * Use `create(ListUserSchema)` to create a new message.
 */
export const ListUserSchema = /*@__PURE__*/
  messageDesc(file_user, 6);

/**
 * Describes the message users.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema = /*@__PURE__*/
  messageDesc(file_user, 7);

/**
 * @generated from service users.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_user, 0);

