// @generated by protoc-gen-es v2.6.0
// @generated from file user.proto (package users, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file user.proto.
 */
export const file_user = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEgV1c2VycyIHCgVFbXB0eSJVCgRVc2VyEgoKAmlkGAEgASgJEhEKCWZpcnN0TmFtZRgCIAEoCRIQCghsYXN0TmFtZRgDIAEoCRIPCgdlbWFpbElkGAQgASgJEgsKA2FnZRgFIAEoBSJWChFDcmVhdGVVc2VyUmVxdWVzdBIRCglmaXJzdE5hbWUYASABKAkSEAoIbGFzdE5hbWUYAiABKAkSDwoHZW1haWxJZBgDIAEoCRILCgNhZ2UYBCABKAUiLAoRVXBkYXRlVXNlclJlcXVlc3QSCgoCaWQYASABKAkSCwoDYWdlGAIgASgFIiUKF0dldEFuZERlbGV0ZVVzZXJSZXF1ZXN0EgoKAmlkGAEgASgJIiUKEkRlbGV0ZVVzZXJSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIgoKCExpc3RVc2VyIi8KEUxpc3RVc2Vyc1Jlc3BvbnNlEhoKBXVzZXJzGAEgAygLMgsudXNlcnMuVXNlcjK2AgoLVXNlclNlcnZpY2USMwoKQ3JlYXRlVXNlchIYLnVzZXJzLkNyZWF0ZVVzZXJSZXF1ZXN0GgsudXNlcnMuVXNlchI6CgtHZXRVc2VyQnlJZBIeLnVzZXJzLkdldEFuZERlbGV0ZVVzZXJSZXF1ZXN0GgsudXNlcnMuVXNlchIzCgpVcGRhdGVVc2VyEhgudXNlcnMuVXBkYXRlVXNlclJlcXVlc3QaCy51c2Vycy5Vc2VyEjgKC0dldFVzZXJMaXN0Eg8udXNlcnMuTGlzdFVzZXIaGC51c2Vycy5MaXN0VXNlcnNSZXNwb25zZRJHCgpEZWxldGVVc2VyEh4udXNlcnMuR2V0QW5kRGVsZXRlVXNlclJlcXVlc3QaGS51c2Vycy5EZWxldGVVc2VyUmVzcG9uc2ViBnByb3RvMw");

/**
 * Describes the message users.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * Describes the message users.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * Describes the message users.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * Describes the message users.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 3);

/**
 * Describes the message users.GetAndDeleteUserRequest.
 * Use `create(GetAndDeleteUserRequestSchema)` to create a new message.
 */
export const GetAndDeleteUserRequestSchema = /*@__PURE__*/
  messageDesc(file_user, 4);

/**
 * Describes the message users.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema = /*@__PURE__*/
  messageDesc(file_user, 5);

/**
 * Describes the message users.ListUser.
 * Use `create(ListUserSchema)` to create a new message.
 */
export const ListUserSchema = /*@__PURE__*/
  messageDesc(file_user, 6);

/**
 * Describes the message users.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema = /*@__PURE__*/
  messageDesc(file_user, 7);

/**
 * @generated from service users.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_user, 0);

